Repository red-hat-storage/noobaa-sa-ci, pull requests merged in 2024-04, with the labels that each got.

#16 Add basic functional S3 tests for standalone NSFS using boto3
  noobaa_sa/account.py
  noobaa_sa/bucket.py
  noobaa_sa/constants.py
  noobaa_sa/exceptions.py
  noobaa_sa/s3_client.py
  tests/conftest.py
  tests/test_account_operations.py
  tests/test_bucket_operations.py
  tests/test_multipart_operations.py
  tests/test_s3_bucket_operations.py
  tests/test_s3_object_operations.py
  utility/nsfs_server_utils.py
  utility/utils.py
Labels: size/XXL

#21 Fix the check for the existence of the `tls.crt` file on the remote machine in `check_nsfs_tls_cert_setup`
  utility/nsfs_server_utils.py
Labels: size/XS

#20 Adds all independent multipart operations
  noobaa_sa/s3_client.py
  tests/test_multipart_operations.py
  utility/bucket_utils.py
Labels: size/L
