Repository red-hat-storage/noobaa-sa-ci, pull requests merged in 2024-05, with the labels that each got.

#24 Changed list_multipart_upload function verification parameters
  tests/test_multipart_operations.py
Labels: size/XS

#23 Changes cli and service names based on latest build
  noobaa_sa/account.py
  noobaa_sa/bucket.py
  noobaa_sa/constants.py
  noobaa_sa/defaults.py
Labels: size/S

#26 Adjust tls related setup to latest permission restrictions
  utility/nsfs_server_utils.py
Labels: size/XS

#28 Fixes noobaa health flags script based on latest changes
  tests/test_health_operations.py
Labels: size/S

#29 Adjust setup related fixtures to the latest changes to noobaa-core
  tests/conftest.py
  utility/nsfs_server_utils.py
  utility/retry.py
  utility/utils.py
Labels: size/L
