Repository red-hat-storage/noobaa-sa-ci, pull requests merged in 2025-01, with the labels that each got.

#47 Adds test coverage[Head object, copy] for versioning feature
  noobaa_sa/s3_client.py
  tests/test_bucket_versioning.py
  tests/test_multipart_operations.py
  utility/bucket_utils.py
  utility/utils.py
Labels: size/L

#49 Adjust the `account_manager` fixture to only delete accounts and buckets that were created in its scope
  noobaa_sa/account.py
  noobaa_sa/bucket.py
  tests/conftest.py
Labels: size/M

#50 Limit Comment Lines to 10 in Email Report
  framework/customizations/reports.py
Labels: size/XS
